# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202305

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [6]:
# create some random matrices
A = np.random.randint(10,size=(3,4))
B = np.random.randint(10,size=(4,5))
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,3)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 39  34 140 158  84]
 [ 71  45 136 161  98]
 [ 49  13 133 165 114]]
 
[[ -9.95 -25.95  -2.1  -25.34]
 [-17.71 -15.01  -5.12  -7.58]
 [-13.85 -22.06  -3.15 -17.35]
 [ 14.3   25.49   2.01  18.31]
 [ -3.14   3.53  -0.28   8.42]
 [  5.31   5.78   2.74   7.03]
 [-12.93 -24.59  -1.15 -16.87]]


# Using pytorch

In [ ]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))